// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUtl1ntz_d8Kw-7Ez07ESkbydAOUs9bh0',
    appId: '1:977432470994:web:5fd33c57caff75ee70940b',
    messagingSenderId: '977432470994',
    projectId: 'codersneed',
    authDomain: 'codersneed.firebaseapp.com',
    storageBucket: 'codersneed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATTVYaTFoCwEVBnmjIy7rBiifGTJWlybk',
    appId: '1:977432470994:android:f0cf423febdace4070940b',
    messagingSenderId: '977432470994',
    projectId: 'codersneed',
    storageBucket: 'codersneed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY9q5thTEHvpAt8U2MylHrx868uOcg2_I',
    appId: '1:977432470994:ios:352fcd6a3fd5c15570940b',
    messagingSenderId: '977432470994',
    projectId: 'codersneed',
    storageBucket: 'codersneed.appspot.com',
    iosBundleId: 'com.example.codequest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY9q5thTEHvpAt8U2MylHrx868uOcg2_I',
    appId: '1:977432470994:ios:352fcd6a3fd5c15570940b',
    messagingSenderId: '977432470994',
    projectId: 'codersneed',
    storageBucket: 'codersneed.appspot.com',
    iosBundleId: 'com.example.codequest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUtl1ntz_d8Kw-7Ez07ESkbydAOUs9bh0',
    appId: '1:977432470994:web:ec934937507528d970940b',
    messagingSenderId: '977432470994',
    projectId: 'codersneed',
    authDomain: 'codersneed.firebaseapp.com',
    storageBucket: 'codersneed.appspot.com',
  );

}